### ISSUE TITLE
In Ada

### ISSUE THREAD

**Issue by ohenley** [tensor-programming/golang-blockchain#1]
Hi Tensor,

If by any chance you have time to undertake this in Ada it would be great.

1) Ada is way underrated and needs adoption. It is a really powerful language. I assume you probably already know it from your Youtube channel banner, element 22. 
2) Ada would be perfect for blockchain, given its high integrity emphasis and native performance.

There is already some base work that can be found here: https://blog.adacore.com/bitcoin-in-ada
Also, do not hesitate to check my awesome-ada page for anything up to date, Ada related. https://github.com/ohenley/awesome-ada

Thx for your time and concern, Keep up the amazing work.

ohenley

**Comment by tensor-programming** [comment]
Sorry, haven't worked enough with Ada to build such a complex system.
